import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/modules/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f9f9f9',
        'on-secondary-fixed': '#071e27',
        'on-primary-fixed': '#410003',
        'tertiary-fixed-dim': '#7ad7c6',
        'on-tertiary-fixed': '#00201b',
        'on-error-container': '#93000a',
        'surface-container': '#eeeeee',
        'inverse-primary': '#ffb3ac',
        'on-secondary-container': '#526772',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#97f3e2',
        'surface-variant': '#e2e2e2',
        'surface-tint': '#ba1a20',
        'secondary-fixed-dim': '#b4cad6',
        primary: '#af101a',
        'on-primary-fixed-variant': '#930010',
        'primary-fixed-dim': '#ffb3ac',
        'inverse-on-surface': '#f1f1f1',
        'on-tertiary-container': '#cefff4',
        'tertiary-container': '#0f7e70',
        'on-secondary-fixed-variant': '#354a53',
        'surface-container-highest': '#e2e2e2',
        'secondary-container': '#cfe6f2',
        secondary: '#4c616c',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        outline: '#8f6f6c',
        'on-surface': '#1a1c1c',
        'surface-container-high': '#e8e8e8',
        'on-background': '#1a1c1c',
        'outline-variant': '#e4beba',
        'on-surface-variant': '#5b403d',
        'surface-container-low': '#f3f3f3',
        'primary-container': '#d32f2f',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3131',
        'error-container': '#ffdad6',
        background: '#f9f9f9',
        'on-primary-container': '#fff2f0',
        'surface-dim': '#dadada',
        tertiary: '#006357',
        'on-tertiary-fixed-variant': '#005047',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'secondary-fixed': '#cfe6f2',
        surface: '#f9f9f9',
        'primary-fixed': '#ffdad6',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0px 12px 32px rgba(65,0,3,0.06)',
      },
    },
  },
  plugins: [],
};

export default config;
